content/architecture.md, content/getting-started/install-application.md
=> added app install instruction and improved app arch

content/_index.md, content/architecture.md, content/concepts/architecture.md, content/getting-started/install-application.md, content/getting-started/install-hub.md, content/getting-started/register-cluster.md, data/menu/more.yaml
fixing some wording, style and spelling.
added manifestwork to showcase hub => managed deployment
=> polishing the website

content/getting-started/install-application.md, content/getting-started/install-hub.md, content/getting-started/register-cluster.md
relies on the foundation changes at https://github.com/open-cluster-management/registration-operator/pull/90
=> easier kind prereq setup. fix register cluster instruction

content/getting-started/install-hub.md, content/getting-started/register-cluster.md
=> refractor instructions to be more generic and less hardcoded example value

content/getting-started/register-cluster.md
=> fixed example for register managed cluster

content/getting-started/install-application.md
=> enhance the app instructions

content/community/resource.md, content/getting-started/install-application.md
=> misc wording fixes

content/concepts/architecture.md
Juliana thinks the current managed cluster description is confusing. So I updated it with the description from the api repo.
=> update managed cluster description

content/community/resource.md, content/concepts/architecture.md, content/getting-started/register-cluster.md
https://github.com/open-cluster-management/backlog/issues/7660
=> Fix some types in website

content/community/resource.md, data/menu/more.yaml
Signed-off-by: Mike Ng <mikeshngdev@gmail.com>
=> added our slack channel

config.toml
Accidentaly discovered the issue in edit this page. Unsure if this is acceptable for you guys. Don't hesitate to reject in case you've other plans or a better fix.
FYI @cdoan1
=> to fix edit this page link

content/community/resource.md, content/contribute/contribute.md, data/menu/more.yaml
minor fixes based on Juliana's review
=> update contribution and youtube link on the main page

content/concepts/architecture.md
Signed-off-by: Dominique Vernier <dvernier@redhat.com>
=> Add cluster lifecycle

content/concepts/architecture.md
=> remove work in progress from app lifecycle

content/concepts/architecture.md, content/getting-started/install-discovery.md
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>
open-cluster-management/backlog#9777
This PR has same changes as - https://github.com/open-cluster-management/website/pull/39 but commit has been signed off.
=> Add discovery - work in progress

content/concepts/architecture.md
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>
https://github.com/open-cluster-management/backlog/issues/9785
=> Add multiclusterhub-repo WIP

content/concepts/architecture.md
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
Related issue: https://github.com/open-cluster-management/backlog/issues/9582
=> add search wip

deploy.sh
=> Fix clone error when publish

content/getting-started/install-policy-controllers.md, content/getting-started/install-policy-framework.md
https://github.com/open-cluster-management/backlog/issues/11335
=> add doc for policy framework and controllers

content/concepts/architecture.md, content/getting-started/install-multiclusterhub-operator.md
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
=> new com with signoff

content/getting-started/install-application.md, content/getting-started/register-cluster.md
Signed-off-by: Philip Wu <phwu@redhat.com>
=> Minor changes to getting started

content/getting-started/install-policy-controllers.md, content/getting-started/install-policy-framework.md
Signed-off-by: Mikela Jackson <mdockery@redhat.com>
=> Update website for GRC

content/getting-started/install-application.md, content/getting-started/install-cluster-manager.md, content/getting-started/install-policy-controllers.md, content/getting-started/install-policy-framework.md, content/getting-started/register-cluster.md
=> update app getting started. be more generic in terms of kube context

content/getting-started/install-cluster-lifecycle.md
Signed-off-by: Hanqiu Zhang <hanzhang@redhat.com>
=> fix possession in cluster-deployment instruction

content/_index.md, content/getting-started/core/cluster-manager.md, content/getting-started/core/register-cluster.md, content/getting-started/integration/app-lifecycle.md, data/menu/more.yaml
As requested by the marketing team and @juliana-hsu , we should expose the community meeting link in the front page. 
Also contains some misc fixes that was missed from earlier PRs.
=> add community meeting link to the front page, and misc fixes from doc reviews

content/getting-started/core/register-cluster.md
=> fix register klusterlet missing export MANAGED_CLUSTER step

content/_index.md, content/blog/_index.md, content/blog/blog.md
the front page has been updated with the blog button at the bottom right
=> add blog section and blog entries to website

content/getting-started/integration/app-lifecycle.md
for https://github.com/open-cluster-management-io/community/issues/43
=> fix deploy app sub to managed cluster instruction

content/clusteradm.md, layouts/_default/clusteradm.html, layouts/sitemap.xml
Signed-off-by: Dominique Vernier <dvernier@redhat.com>
=> Add clusteradm

deploy.sh
=> Change cname

config.toml, content/getting-started/quick-start/_index.md
=> fixed link for quick start and re-enable edit button

OWNERS
This PR adds 'gurnben' to the list of users - I'll be handling domain mapping and some website maintenance tasks!
=> Add 'gurnben' to owners for website maintenance

content/_index.md, content/getting-started/integration/_index.md, content/getting-started/integration/app-lifecycle.md, content/getting-started/integration/policy-controllers.md, content/getting-started/integration/policy-framework.md, themes/hugo-geekdoc/layouts/partials/site-footer.html
- hide app, policy. 
- add copyright.
- modify landing page to reflect changes
=> align website with accelerated cncf submission proposal

Makefile, deploy.sh
=> fix deploy website

content/getting-started/quick-start/_index.md
Signed-off-by: Dominique Vernier <dvernier@redhat.com>
=> Add clusteradm instruction

Makefile, deploy.sh
=> fix deploy

content/_index.md, content/getting-started/integration/_index.md, content/getting-started/integration/app-lifecycle.md
=> re-enable applifecycle steps

content/concepts/addon.md, content/concepts/managedcluster.md, content/concepts/manifestwork.md, content/concepts/placement.md
=> Add placement design

content/concepts/roadmap.md
=> point roadmap to github project

content/_index.md, content/community/releases.md
=> add release page

content/community/releases.md
=> adjust release cycle

content/addon-framework.md, layouts/_default/addon-framework.html, layouts/sitemap.xml
=> Add addon-framework goref

content/concepts/addon.md, content/getting-started/integration/_index.md
=> replace addon references to add-on

content/getting-started/integration/policy-controllers.md, content/getting-started/integration/policy-framework.md
to address the comments in https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/108#pullrequestreview-698554404
=> fix policy framework deployment step

content/getting-started/core/cluster-manager.md, content/getting-started/core/register-cluster.md
=> Update core base on new registration-operator repo readme.md

content/getting-started/integration/policy-controllers.md, content/getting-started/integration/policy-framework.md
Add some space between commands
Before:
After:
=> Update integration policy

CONTRIBUTING.md, content/_index.md, content/community/resource.md, content/concepts/architecture.md, content/contribute/contribute.md
=> fix github links

content/getting-started/integration/policy-framework.md
- Make propagator link more visible
- Add "what is next" to install controllers
=> Minor GRC tweaks

content/_index.md, content/concepts/addon.md, content/concepts/architecture.md, content/concepts/managedcluster.md, content/concepts/manifestwork.md, content/concepts/placement.md, content/getting-started/integration/app-lifecycle.md, content/getting-started/integration/policy-framework.md, content/getting-started/quick-start/_index.md
Signed-off-by: chenz4027 <magchen@redhat.com>
https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/112
=> Fix issue #112

content/getting-started/integration/app-lifecycle.md
=> use the new app addon for deployment instruction

content/getting-started/core/register-cluster.md, content/getting-started/integration/policy-framework.md, content/getting-started/quick-start/_index.md
Signed-off-by: chenz4027 <magchen@redhat.com>
https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/114
=> Fix and rephrase documentation

content/concepts/architecture.md
=> Add overview based on Michael's comment

content/concepts/managedcluster.md
Fix incorrect ManagedCluster label
=> Fix incorrect ManagedCluster label

themes/hugo-geekdoc/layouts/partials/head/custom.html
=> add analytic tracking

content/getting-started/integration/policy-framework.md
Depends on merge of:
- https://github.com/open-cluster-management/governance-policy-framework/pull/125
=> Update GRC architecture link

content/community/releases.md
=> update release dates

content/getting-started/integration/policy-framework.md
Signed-off-by: Gus Parvin <gparvin@redhat.com>
@dhaiducek noticed our description just mentioned prereqs and not what the policy framework was.
This description was taken from https://github.com/open-cluster-management/governance-policy-framework#governance-policy-framework
=> description of policy framework

content/concepts/addon.md, content/concepts/manifestwork.md
1. Changes "responsible" to "responsibility" in addon.md
2. Removes an extra "the" in manifestwork.md
Signed-off-by: Jaanki <jchhatba@redhat.com>
=> Make few edits to the write-up

content/concepts/placement.md
Ref: https://github.com/open-cluster-management/backlog/issues/16066
=> update placement concept

content/concepts/manifestwork.md
=> Add delete option

i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/subject.html, themes/ocmTheme/static/main.css
=> add github link

content/en/community/releases.md, content/zh/community/releases.md
=> Add 0.5 release note

themes/ocmTheme/layouts/index.html, themes/ocmTheme/layouts/partials/cncf.html, themes/ocmTheme/layouts/partials/footer.html, themes/ocmTheme/static/main.css
=> add cncf logo and trademark usage

content/en/getting-started/integration/app-lifecycle.md, content/zh/getting-started/integration/app-lifecycle.md
=> Add install using clusteradm step to app lifecycle page

content/en/concepts/addon.md, content/en/concepts/managedcluster.md, content/en/concepts/manifestwork.md, content/en/concepts/placement.md
=> Some apiversions are missing in the examples

content/en/getting-started/quick-start/_index.md
=> Doc: Polishing the content of quick start

content/en/getting-started/quick-start/_index.md
=> Doc: Rephrase managed cluster requirement for clarification

content/en/concepts/architecture.md
=> Doc: Polish the arch overview doc

content/en/community/roadmap.md
=> Fix Roadmap link

content/en/multicloud-operators-subscription.md, layouts/_default/multicloud-operators-subscription.html, layouts/sitemap.xml
For https://github.com/open-cluster-management-io/multicloud-operators-subscription/issues/48
=> Add go mod ref for app repos

content/en/getting-started/quick-start/_index.md
=> Doc: Convinient way to install clusteradm

content/en/getting-started/quick-start/_index.md
Signed-off-by: yue9944882 <291271447@qq.com>
=> Chore: GetStart doc minor fixes

content/en/scenarios/extending-managed-clusters.md, content/zh/scenarios/extending-managed-clusters.md, i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/sidebar.html
=> Doc: Extending managed cluster model

content/en/concepts/managedcluster.md, content/zh/concepts/managedcluster.md
=> Doc: Polish managed cluster doc

content/en/concepts/managedcluster.md, content/zh/concepts/managedcluster.md
=> Chore: Managed cluster TOC

content/en/getting-started/integration/managed-serviceaccount.md, content/zh/getting-started/integration/managed-serviceaccount.md, i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/sidebar.html
=> Doc: Managed service account

content/en/cluster-proxy.md, content/en/managed-serviceaccount.md, layouts/_default/cluster-proxy.html, layouts/_default/managed-serviceaccount.html, layouts/sitemap.xml
=> Go get cluster-proxy / managed-serviceaccount

content/en/contribute/_index.md
=> Use OCM repo as the generic place to open issues.

themes/ocmTheme/layouts/partials/sidebar.html
=> update community meetings link

content/en/getting-started/integration/cluster-proxy.md, content/en/getting-started/quick-start/_index.md, content/en/scenarios/pushing-kube-api-requests.md, content/zh/getting-started/integration/cluster-proxy.md, content/zh/scenarios/pushing-kube-api-requests.md, i18n/zh.toml
=> Doc: Clarifying cluster-proxy updates in the v0.1.1 release

content/en/getting-started/quick-start/_index.md
=> Doc: Recommend --wait flags for better user-experience

content/en/scenarios/deploy-kubernetes-resources.md
Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>
Fixes https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/187
=> fix crd name

content/en/getting-started/quick-start/_index.md
Signed-off-by: morvencao <lcao@redhat.com>
=> small fixes for quick start.

content/en/concepts/architecture.md
=> fix some typo in Modularity and extensibility part

content/en/community/releases.md, content/zh/community/releases.md
=> Add 0.6.0 release date

themes/ocmTheme/layouts/partials/head.html
=> re-enable analytic tracking

content/en/concepts/placement.md
The related feature request: open-cluster-management-io/community#52
Ref: https://github.com/open-cluster-management/backlog/issues/18210
=> update placement with extensible scheduling

content/en/concepts/architecture.md, content/en/scenarios/pushing-kube-api-requests.md, content/zh/scenarios/pushing-kube-api-requests.md
=> replace word master with main

content/en/concepts/architecture.md, content/zh/concepts/architecture.md
Relevant issue:https://github.com/open-cluster-management-io/OCM/issues/21
=> "concepts/architecture.md"  translation

content/en/blog/_index.md
=> add placement blog

content/en/getting-started/quick-start/_index.md
For https://github.com/open-cluster-management-io/clusteradm/issues/109
=> Add a note for clusteradm join command when using KinD clusters

content/en/community/releases.md, content/zh/community/releases.md
=> Add 0.6 release announce

content/en/concepts/placement.md, content/zh/concepts/placement.md
Ref: https://github.com/stolostron/backlog/issues/19189
https://github.com/open-cluster-management-io/community/issues/126
=> update Placement and PlacementDecision API to v1beta1

content/en/getting-started/quick-start/_index.md
I missed this spot in the previous https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/201
=> Update quick start guide with a note for KinD cluster

content/en/getting-started/administration/_index.md, content/en/getting-started/administration/upgrading.md, content/zh/getting-started/administration/_index.md, content/zh/getting-started/administration/upgrading.md, i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/sidebar.html
=> Doc: Adding a doc for admin about upgrading OCM

content/en/concepts/managedcluster.md, content/zh/concepts/managedcluster.md
Signed-off-by: Ricardo Carrillo Cruz <ricarril@redhat.com>
=> Fix heartbeats text on ManagedCluster concepts web page

content/en/getting-started/quick-start/_index.md
This allows to just press ENTER to run them
Signed-off-by: Ricardo Carrillo Cruz <ricarril@redhat.com>
=> Remove dollars from copy paste snippets

content/en/concepts/addon.md, content/en/concepts/manifestwork.md, content/en/concepts/placement.md, content/en/getting-started/integration/app-lifecycle.md, content/en/getting-started/quick-start/_index.md, content/en/scenarios/deploy-kubernetes-resources.md
Hello
I've been going through the documentation and I bumped into a couple of small typos needed to be fixed.
=> docs: small typos and fixups

content/en/concepts/placement.md, content/en/getting-started/integration/policy-controllers.md, content/en/getting-started/integration/policy-framework.md, content/zh/concepts/managedclusterset.md, content/zh/concepts/placement.md
Primarily, fixes the Policy CRD link. Also includes some additional polishing and fixing links in the ManagedClusterSet and Placement pages.
=> Update GRC docs

content/en/concepts/managedclusterset.md, content/zh/concepts/managedclusterset.md
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
=> fix: modify document due to command change

content/en/concepts/managedclusterset.md, content/zh/concepts/managedclusterset.md
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
=> add default managedclusterset introduction

content/en/concepts/managedcluster.md, content/en/concepts/placement.md, content/zh/concepts/managedcluster.md, content/zh/concepts/placement.md
Ref: https://github.com/open-cluster-management-io/community/issues/48
=> add Taint and Toleration

content/en/getting-started/core/cluster-manager.md, content/en/getting-started/core/register-cluster.md, content/en/getting-started/integration/app-lifecycle.md, content/en/getting-started/integration/policy-controllers.md, content/en/getting-started/integration/policy-framework.md, content/zh/getting-started/core/cluster-manager.md, content/zh/getting-started/core/register-cluster.md, content/zh/getting-started/integration/app-lifecycle.md, content/zh/getting-started/integration/policy-controllers.md, content/zh/getting-started/integration/policy-framework.md
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
seems that kustomize installation link is changed, repalce it with new link
=> reset kustomize installition link

content/en/getting-started/integration/app-lifecycle.md, content/zh/getting-started/integration/app-lifecycle.md
=> Fix application manager addon deploy name on the managed cluster

content/en/getting-started/quick-start/_index.md, content/en/scenarios/deploy-kubernetes-resources.md, content/zh/getting-started/quick-start/_index.md, content/zh/scenarios/deploy-kubernetes-resources.md, themes/ocmTheme/layouts/partials/subject.html
Also add next step in getting started page
=> Update doc for deploy k8s resource

content/en/concepts/managedcluster.md, content/en/concepts/placement.md, content/zh/concepts/managedcluster.md, content/zh/concepts/placement.md
=> clarify PreferNoSelect implementation

content/en/getting-started/integration/policy-framework.md, content/zh/getting-started/integration/policy-framework.md
=> Remove wrong link and update policy content

content/en/scenarios/deploy-kubernetes-resources.md
related to https://github.com/open-cluster-management-io/registration/issues/221
=> update doc to make manifestsworks clearer

content/en/concepts/addon.md, content/en/concepts/managedclusterset.md, content/en/getting-started/integration/app-lifecycle.md, content/en/getting-started/integration/policy-framework.md, content/zh/getting-started/integration/app-lifecycle.md, content/zh/getting-started/integration/policy-framework.md
- Updates app to use `hub-addon` command:
- https://github.com/open-cluster-management-io/clusteradm/pull/175
- Adds policy-framework `clusteradm` command:
- https://github.com/open-cluster-management-io/clusteradm/pull/170
- Fixes some broken links
=> Add `hub-addon` docs for policy framework

content/en/community/roadmap.md, content/zh/community/roadmap.md
=> update roadmap link

content/en/community/releases.md, content/zh/community/releases.md
=> Add 0.7 release note

content/zh/scenarios/pushing-kube-api-requests.md
so that readers can directly copy/paste
=> Doc: Properly escape the newline

content/en/getting-started/integration/app-lifecycle.md, content/zh/getting-started/integration/app-lifecycle.md
=> Optimize the doc for app cycle

content/zh/concepts/addon.md
Signed-off-by: panguicai008 <1121906548@qq.com>
=> fix aspects typo

content/en/getting-started/integration/managed-serviceaccount.md, content/zh/getting-started/integration/managed-serviceaccount.md
=> Add more input/info for service account doc

content/en/getting-started/integration/policy-framework.md, content/zh/getting-started/integration/policy-framework.md
=> update policy doc to make it easy for read

content/en/getting-started/integration/policy-framework.md
Templates in policies are useful to control content so policies can
contain dynamic instead of static content.  This can result in fewer
policies needed to cover a wider range of systems.
Refs:
- https://github.com/stolostron/backlog/issues/22480
Signed-off-by: Gus Parvin <gparvin@redhat.com>
=> Add some documentation around templates in config policies

i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/subject.html
For https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/264
=> Add a join Slack button on the OCM io homepage

content/en/community/releases.md
=> Add 0.8.0 release date

content/en/concepts/managedclusterset.md, content/zh/concepts/managedclusterset.md
Signed-off-by: ldpliu <daliu@redhat.com>
=> add global clusterset

content/en/scenarios/distribute-workload-with-placement.md, content/zh/scenarios/distribute-workload-with-placement.md, i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/sidebar.html
Ref: https://github.com/open-cluster-management-io/OCM/issues/33
=> distribute work with placement

content/en/concepts/manifestwork.md, content/zh/concepts/manifestwork.md
=> Update strategy doc

themes/ocmTheme/layouts/partials/header.html, themes/ocmTheme/layouts/partials/sidebar.html
=> Update youtube URL

content/en/community/releases.md
=> Add 0.8.0 release notes

content/en/community/releases.md, content/zh/community/releases.md
=> Update release note

content/en/getting-started/integration/policy-controllers.md, content/en/getting-started/integration/policy-framework.md, content/zh/getting-started/integration/policy-controllers.md, content/zh/getting-started/integration/policy-framework.md
Depends on:
- https://github.com/open-cluster-management-io/clusteradm/pull/229
Addresses:
- https://github.com/stolostron/backlog/issues/16046
- https://github.com/open-cluster-management-io/community/issues/122
=> Update `policy-framework` docs for `clusteradm`

content/en/getting-started/integration/app-lifecycle.md, content/en/scenarios/deploy-kubernetes-resources.md, content/zh/getting-started/integration/app-lifecycle.md, content/zh/scenarios/deploy-kubernetes-resources.md
based on 
```
Options:
--clusters='': Names of the managed cluster to apply work
Options:
--annotate=[]: Annotations to add to the ManagedClusterAddon (eg. key1=value1,key2=value2)
--clusters=[]: Names of the managed cluster to deploy the add-on to (comma separated)
--names=[]: Names of the add-on to deploy (comma separated)
```
=> update with --clusters and --names

content/en/scenarios/deploy-kubernetes-resources.md, content/zh/scenarios/deploy-kubernetes-resources.md
=> update sample output for multiple commands

content/en/concepts/addon.md, content/en/concepts/architecture.md, content/en/scenarios/pushing-kube-api-requests.md, content/zh/concepts/addon.md, content/zh/concepts/architecture.md, content/zh/scenarios/pushing-kube-api-requests.md
=> fix typo Addon => AddOn

content/en/getting-started/quick-start/_index.md
for https://github.com/open-cluster-management-io/clusteradm/issues/251
=> Update Kubernetes version requirement and advice user to use latest KinD version

content/en/developer-guides/_index.md, content/en/developer-guides/addon.md, content/zh/developer-guides/_index.md, content/zh/developer-guides/addon.md, i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/sidebar.html
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
task: https://github.com/open-cluster-management-io/OCM/issues/32
add a sidebar Developer Guides like this
=> add how to develop an add-on using add-on framework

content/en/concepts/architecture.md
For fixing https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/206
=> Fixed minor spelling and grammar mistakes on the arch page

content/en/contribute/_index.md, content/en/scenarios/extend-multicluster-scheduling-capabilities.md, content/zh/contribute/_index.md, content/zh/scenarios/extend-multicluster-scheduling-capabilities.md, themes/ocmTheme/layouts/partials/header.html, themes/ocmTheme/layouts/partials/sidebar.html, themes/ocmTheme/layouts/partials/subject.html
=> Update Slack URL to be more user friendly.

content/en/concepts/managedclusterset.md, content/en/concepts/placement.md, content/zh/concepts/managedclusterset.md, content/zh/concepts/placement.md
Ref: https://github.com/open-cluster-management-io/community/issues/145
=> doc api changes

content/en/concepts/placement.md, content/zh/concepts/placement.md
Ref: https://github.com/open-cluster-management-io/OCM/issues/66
=> doc how to troubleshoot placement

content/en/developer-guides/addon.md
=> add doc for add-on config

content/en/getting-started/integration/policy-controllers.md, content/en/getting-started/integration/policy-framework.md, content/zh/getting-started/integration/policy-controllers.md, content/zh/getting-started/integration/policy-framework.md
Recent unreleased changes to the main branch change the installation instructions, which motivated this change.
=> Pin the policy component versions

content/en/concepts/managedclusterset.md, content/zh/concepts/managedclusterset.md
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/open-cluster-management-io/OCM/issues/77
=> Update clusterset v1beta2

content/en/getting-started/integration/policy-framework.md, content/zh/getting-started/integration/policy-framework.md
This also pins the version to 0.9.0 in the Policy documentation.
Relates:
https://github.com/stolostron/backlog/issues/25999
=> Document the consolidated policy controller

content/en/blog/_index.md, content/en/scenarios/integration-with-argocd.md, content/zh/blog/_index.md, content/zh/scenarios/integration-with-argocd.md
Signed-off-by: Maggie Chen <magchen@redhat.com>
=> Add the slide for integration with ArgoCD

content/en/concepts/placement.md, content/zh/concepts/placement.md
=> update placement decision description

content/en/placement.md, content/en/registration.md, content/en/work.md, layouts/_default/placement.html, layouts/_default/registration.html, layouts/_default/work.html, layouts/sitemap.xml
=> Expose core library

content/en/community/releases.md, content/zh/community/releases.md
=> Add release-0.9 notes

content/en/scenarios/extend-multicluster-scheduling-capabilities.md, content/zh/scenarios/extend-multicluster-scheduling-capabilities.md
Ref: https://github.com/open-cluster-management-io/OCM/issues/69
=> update extensible scheduling example repo

content/en/multicluster-controlplane.md, layouts/_default/multicluster-controlplane.html, layouts/sitemap.xml
Signed-off-by: myan <myan@redhat.com>
=> Expose multicluster-controlplane library

content/en/concepts/clusterclaim.md, content/zh/concepts/clusterclaim.md, i18n/en.toml, i18n/zh.toml, themes/ocmTheme/layouts/partials/sidebar.html
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
=> add clusterclaim in concept

content/en/concepts/managedclusterset.md, content/zh/concepts/managedclusterset.md
=> add ManagedClusterSetBinding

content/en/getting-started/quick-start/_index.md
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>
=> update join process

themes/ocmTheme/static/main.css
=> set list and body font size to be same

content/en/developer-guides/addon.md, content/zh/developer-guides/addon.md
=> update addon developer guide

content/en/concepts/managedclusterset.md, content/zh/concepts/managedclusterset.md
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
=> update the managedclusterset concept

content/en/concepts/placement.md, content/zh/concepts/placement.md
=> update placement prioritizer

content/en/concepts/manifestwork.md, content/zh/concepts/manifestwork.md
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
issues: 
https://github.com/open-cluster-management-io/work/issues/173
https://github.com/open-cluster-management-io/OCM/issues/118
=> add apply job using mainfestWork

content/en/getting-started/installation/register-a-cluster.md, content/en/getting-started/installation/start-the-control-plane.md
Signed-off-by: Meng [yanmxa@163.com](mailto:yanmxa@163.com)
Ref: https://github.com/open-cluster-management-io/clusteradm/issues/307
=> add instructions for uninstalling OCM

content/en/concepts/managedcluster.md, content/en/getting-started/integration/cluster-proxy.md, content/zh/getting-started/integration/cluster-proxy.md
Signed-off-by: myan [myan@redhat.com](mailto:myan@redhat.com)
=> correct document spelling issues

content/en/ocm-kustomize-generator-plugins.md, content/en/policy-generator-plugin.md, layouts/_default/ocm-kustomize-generator-plugins.html, layouts/_default/policy-generator-plugin.html, layouts/sitemap.xml
ref: https://issues.redhat.com/browse/ACM-2598
=> Update generator redirects

content/en/blog/_index.md
Signed-off-by: Tomer Figenblat <tfigenbl@redhat.com>
=> docs: added distribute workloads using kind blog article

content/zh/blog/access-cluster-in-different-vps/_index.md
In this way, the images can also be review at GitHub: https://github.com/xuezhaojun/open-cluster-management-io.github.io/blob/change-image-path-to-relative-path/content/zh/blog/access-cluster-in-different-vps/_index.md
=> Change image paths to relative paths.

themes/ocmTheme/layouts/404.html, themes/ocmTheme/layouts/_default/baseof.html, themes/ocmTheme/layouts/_default/list.html, themes/ocmTheme/layouts/_default/single.html
resolve https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/345
=> add lang tag to html

themes/ocmTheme/layouts/partials/supports.html
resolve https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/347
=> add alt to img

themes/ocmTheme/layouts/partials/header.html
resolve https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/351
=> Accessibility add link name to icons

content/en/ocm.md, layouts/_default/ocm.html, layouts/sitemap.xml
add `ocm` go module reference.
=> add go mod ref

themes/ocmTheme/layouts/partials/header.html, themes/ocmTheme/static/main.css
resolve https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/368
=> fix navigation button on mobile

content/en/governance-policy-nucleus.md
Without this, the import doesn't work.
=> Add page for governance-policy-nucleus

content/en/developer-guides/addon.md, content/zh/developer-guides/addon.md
Fix https://github.com/open-cluster-management-io/ocm/issues/226
=> Add permission description for template addon registration

content/en/scenarios/deploy-kubernetes-resources.md
1. Adding syntax highlighting enhances readability for the readers.
2. Rectifying the representation of command-line inputs for consistency throughout the article.
3. Adjusting proper indentation for improved formatting.
=> Optimize file content in deploy-kubernetes-resources

content/en/scenarios/extend-multicluster-scheduling-capabilities.md
1. [clusteradm](https://github.com/open-cluster-management-io/clusteradm) is updated,correct spelling of output table https://github.com/open-cluster-management-io/clusteradm/pull/218 ,Consequently, the output values are being reconfigured.
2. Adding syntax highlighting enhances readability for the readers.
=> Updated due to a clusteradm update.

content/en/concepts/managedclusterset.md, content/zh/concepts/managedclusterset.md
Ref: https://github.com/open-cluster-management-io/ocm/issues/67
=> update clusterset api change

content/en/developer-guides/addon.md, content/zh/developer-guides/addon.md
Issue reference: https://github.com/open-cluster-management-io/ocm/issues/280
=> Update permission config description in addontemplate

content/en/getting-started/integration/policy-controllers/configuration-policy.md, content/zh/getting-started/integration/policy-controllers/configuration-policy.md
=> Update policy links to OCM-io

themes/ocmTheme/layouts/partials/footer.html
resolve https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/407
=> update current date

content/en/concepts/placement.md, content/zh/concepts/placement.md
PR reference: https://github.com/open-cluster-management-io/ocm/pull/480
=> Add a note that placement will not select clusters in terminating state

content/en/developer-guides/addon.md, content/zh/developer-guides/addon.md
Fix https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/424#discussion_r1665826637
=> Fix broken links

content/en/registration.md, layouts/_default/registration.html, layouts/sitemap.xml
https://github.com/open-cluster-management-io/registration/issues/323
/assign @skeeey
=> Add regitration lib link back

content/en/docs/developer-guides/addon.md
https://github.com/open-cluster-management-io/ocm/issues/688
=> 📖 Add description for signingCA namespace

content/en/docs/developer-guides/addon.md
https://github.com/open-cluster-management-io/ocm/issues/761
=> 📖 Developer guild for configuring proxy for template type addons

README.md, hugo.yaml
Based on the requirement of: https://www.netlify.com/legal/open-source-policy/
=> Add netlify into doc website.

hugo.yaml
Waiting for the DNS redirect done.
=> Update hugo.yaml to support versioning, currently includes main.

content/en/docs/concepts/add-on-extensibility/_index.md, content/en/docs/concepts/add-on-extensibility/addon.md, content/en/docs/getting-started/_index.md, content/en/docs/getting-started/administration/_index.md, content/en/docs/getting-started/installation/addon-management.md, content/en/docs/getting-started/integration/_index.md, content/en/docs/getting-started/integration/policy-controllers/_index.md, content/en/docs/getting-started/integration/policy-controllers/configuration-policy.md, content/en/docs/getting-started/integration/policy-controllers/gatekeeper.md
ref: https://github.com/open-cluster-management-io/ocm/issues/781
=> move addon operations to getting-started

hugo.yaml
enable search in the website banner
ref: https://github.com/open-cluster-management-io/ocm/issues/781
=> enable offline search

content/en/docs/scenarios/distribute-workload-with-placement.md
Signed-off-by: August Simonelli <asimonel@redhat.com>
=> remove extra command in copypaste text block in distrib workload example

content/en/docs/security/_index.md
=> Add English security reporting page

content/en/blog/joining-hub-and-spoke-with-aws-auth-manually/index.md, content/en/blog/joining-hub-and-spoke-with-aws-auth/index.md
Update documentation by removing the word manually
=> remove manually

assets/scss/_styles_project.scss, content/en/_index.md
This PR updates the OCM adopters section on the website from [ADOPTERS.md](https://github.com/open-cluster-management-io/ocm/blob/main/ADOPTERS.md).
Closes open-cluster-management-io/ocm#848
- Updated `content/en/_index.md` to include the latest adopters.
- Modified styles in `assets/scss/_styles_project.scss` for better presentation.
=> [OCM Incubation] Update OCM adopters on the website #848

content/en/docs/developer-guides/addon.md, content/en/docs/getting-started/integration/app-lifecycle.md
Ref: https://github.com/open-cluster-management-io/ocm/issues/951
=> Update Application Management Addon to use the new Argo CD Addon

hugo.yaml
Also allow user to switch back to main.
=> Update version to v0.16 in hugo.yaml

hugo.yaml
adjust hugo.yaml to enableGitInfo: false
=> remove last mod from pages

content/en/_index.md
update main page ecosystem URLs
Refs: https://github.com/open-cluster-management-io/ocm/pull/1150
=> update main page ecosystem URLs
