- content/getting-started/install-hub.md
- content/getting-started/register-cluster.md
Based on a dev's feedback, added `docker` as requirement for `kind`
also it seems like in order to use the `--internal` to get the proper ip address for hub secret. we must use `kind v0.7.0`. It might be due to a kind bug `https://github.com/kubernetes-sigs/kind/issues/1916`
> update kind info

- content/getting-started/install-application.md
- content/getting-started/install-hub.md
- content/getting-started/register-cluster.md
another feedback improvement from a dev, we need to specify `golang` requirement if we are installing from source.
> add golang as prereq

- content/community/resource.md
- content/contribute/_index.md
- content/contribute/contribute.md
@swopeb one of the feedback we got from the playback is that there is no "Contribute" section on our website. Turns out it's sort of hidden in the "Community" part. I created a dedicated section for "Contribute" with more contents and copied some Community stuffs over. But I feel like there is still some overlapping with "Community". Could you please take a look and comment? Thanks.
> add contribute section

- CONTRIBUTING.md
- DCO
- SECURITY.md
- content/concepts/architecture.md
- content/concepts/roadmap.md
Signed-off-by: Richie Piya <rpiyasirisilp@gmail.com>
https://github.com/open-cluster-management/backlog/issues/9628
These 2 subsections are a part of the "Concepts" section in the project page: https://open-cluster-management.io
**1. Architecture**
**2. Roadmap**
> add app-ui content to project page

- content/getting-started/install-application.md
- content/getting-started/install-hub.md
- content/getting-started/register-cluster.md
This PR goes together with https://github.com/open-cluster-management/registration-operator/pull/103 and addresses https://github.com/open-cluster-management/registration-operator/issues/102. 
The instructions for the patched version have been tested on OS X and Linux.
Signed-off-by: Paolo Dettori <dettori@us.ibm.com>
> Update docs to support OS X for getting started and use kind version >= 0.7

- content/_index.md
- content/getting-started/install-application.md
- content/getting-started/install-cluster-manager.md
- content/getting-started/install-discovery.md
- content/getting-started/install-multiclusterhub-operator.md
- content/getting-started/install-policy-controllers.md
- content/getting-started/install-policy-framework.md
- content/getting-started/register-cluster.md
- Rename most of the hub reference to cluster manager
- After discussing with the open source install guild representative, we decided that the install instructions are not community read, so hide those pages for now.
- Some broken link fixes
> rename most of the hub reference to cluster manager, disable install related guides for now

- content/concepts/architecture.md
This will point to the https://github.com/open-cluster-management/community/raw/main/assets/ocm-arch.png
which is being updated in https://github.com/open-cluster-management/community/pull/37 to include the newly presented policy.
FYI @juliana-hsu
> add a pointer to community arch diag

- config.toml
- content/getting-started/install-cluster-lifecycle.md
- content/getting-started/install-policy-controllers.md
- content/getting-started/install-policy-framework.md
- themes/hugo-geekdoc/layouts/partials/site-footer.html
quick fixes.
currently, our web site has a lot of hugo/geekdoc related items
after removing all the hugo/geekdoc looks like this
> remove some hugo geek doc specific links and some minor fixes to cluster and policy

- content/getting-started/install-policy-controllers.md
- content/getting-started/install-policy-framework.md
has a dependencies on the following PRs:
https://github.com/open-cluster-management/governance-policy-framework/pull/100
https://github.com/open-cluster-management/iam-policy-controller/pull/52
https://github.com/open-cluster-management/cert-policy-controller/pull/86
https://github.com/open-cluster-management/config-policy-controller/pull/119
> update policy instructions to be compatible with non kind clusters

- content/getting-started/core/cluster-manager.md
- content/getting-started/core/register-cluster.md
- content/getting-started/integration/app-lifecycle.md
FYI @berenss the `## Install community operator from OperatorHub.io` change will update both the link and the header. Thanks.
Scott wants to make the following changes:
> update the instruction for installing from operatorhub

- content/getting-started/core/register-cluster.md
Quick start not work since the wrong env/cli expression there.
> Correct wrong env/cli in klusterlet agent installation

- config.toml
Fix on mobile the website is redirecting to `http://open-cluster-management.github.io` on clicking the top banner.
Maybe we should consider actually decommission that legacy website as well @qiujian16 @gurnben
> fix base url

- content/getting-started/core/register-cluster.md
If managed clusters are OKD or OpenShift, the kubeconfig should contain `certificate-authority-data`, `client-certificate-data` and `client-key-data`, or the managed cluster registration will fail with below error.
```
... 
- lastTransitionTime: "2021-07-02T02:15:42Z"
message: 'Failed to create &SelfSubjectAccessReview{ObjectMeta:{      0 0001-01-01
00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:SelfSubjectAccessReviewSpec{ResourceAttributes:&ResourceAttributes{Namespace:,Verb:get,Group:certificates.k8s.io,Version:,Resource:certificatesigningrequests,Subresource:,Name:,},NonResourceAttributes:nil,},Status:SubjectAccessReviewStatus{Allowed:false,Reason:,EvaluationError:,Denied:false,},}
with hub config secret "open-cluster-management-agent" "hub-kubeconfig-secret":
Post …
```
> Prepare kubeconfig with correct format

- content/getting-started/core/cluster-manager.md
- content/getting-started/core/register-cluster.md
- content/getting-started/integration/app-lifecycle.md
- content/getting-started/integration/policy-controllers.md
- content/getting-started/integration/policy-framework.md
- content/getting-started/quick-start/_index.md
This PR tries to enhance the document:
- set some common environment variables at the beginning of the whole guideline.
- try to reduce the kube context switch, for example, `clusteradm` support `--context` flag, so we can use that to quickly refer to the expected kube context.
- reduce duplicated environment variable definition, for example, `MANAGED_CLUSTER_NAME` can be exported after the cluster is created by the `kind` command and then it will be reused throughout the guideline.
- fix typo.
Signed-off-by: morvencao <lcao@redhat.com>
> set common env and reduce the kube context switch.

- content/getting-started/core/register-cluster.md
I am try to debug my  `managedcluster` status  `Unknown` issue by this cmd :
```
Error from server (NotFound): managedclusters.cluster.open-cluster-management.io "llhu-2--context" not found
Error from server (NotFound): managedclusters.cluster.open-cluster-management.io "kind-llhu-adm" not found
```
It should be cmd issue, Thanks
> fix the debug command issue

- content/en/scenarios/deploy-kubernetes-resources.md
the previous revision of this doc put the tutorial about placement API and work API together, however for now the two api are actually irrevalent. this pull removes placement related APIs from the doc and polished the content about how to operate the managed cluster via work API. i will extract the placement tutorials in another doc in a follow-up PR.
> Updating the scenario doc: deploy kubernetes resource via work

- content/en/getting-started/quick-start/_index.md
While following the quick-start step-by-step, i got a wrong output in  _Deploy a cluster manager on your hub cluster_ https://open-cluster-management.io/getting-started/quick-start/#deploy-a-cluster-manager-on-your-hub-cluster  at step 2 checking out the running instances. 
found that the reason is i'm using the context "kind-cluster1" while running the command `$ kubectl -n open-cluster-management   get pod` ,which means that i'm in the wrong context. (while i created a new kind cluster, the context will be automatically change to the new created one, and in the quick-start, we create "cluster1" after "hub". So i'm running the command in "cluster1", surely i can't get the right output)
in my opinion, set the `--context` option explicitly to these commands will make it easier for …
> updating the quick-start doc: deploy a cluster manager step2

- content/en/config-policy-controller.md
- content/en/governance-policy-propagator.md
- content/en/governance-policy-spec-sync.md
- content/en/governance-policy-status-sync.md
- content/en/governance-policy-template-sync.md
- content/en/ocm-kustomize-generator-plugins.md
- layouts/_default/config-policy-controller.html
- layouts/_default/governance-policy-propagator.html
- layouts/_default/governance-policy-spec-sync.html
- layouts/_default/governance-policy-status-sync.html
- layouts/_default/governance-policy-template-sync.html
- layouts/_default/ocm-kustomize-generator-plugins.html
- layouts/sitemap.xml
We're going to update all of our repositories to use the `open-cluster-management.io` domains in the community.
- https://github.com/open-cluster-management/backlog/issues/18572
> Add Go package redirects for GRC

- content/en/getting-started/integration/managed-serviceaccount.md
The install command for managed-serviceaccount addon is incorrect, looks like someone copied it from cluster-proxy addon.
Signed-off-by: morvencao <lcao@redhat.com>
> fix error command for managed-serviceaccount addon.

- content/en/getting-started/integration/app-lifecycle.md
Fix issue with `clusteradm addon enable --name application-manager --clusters ${MANAGED_CLUSTER_NAME}` command
Error: unknown flag: --clusters
We should use `--cluster` flag
> docs: correct spelling in clusteradm command

- OWNERS
I would like the bot to not pick @gurnben as the reviewer for PRs.
Not including in this PR but I feel like @yue9944882 should be added as approver and reviewer in this file. What do you think @yue9944882 ?
> Remove gurnben as reviewer.

- content/en/getting-started/quick-start/_index.md
My observation is that the output of the command in [step 2](https://open-cluster-management.io/getting-started/quick-start/#deploy-a-cluster-manager-on-your-hub-cluster) is not correct because we don't see `klusterlet-work-agent` until we approve the CSR
```shell
kubectl -n open-cluster-management-agent get pod --context ${CTX_MANAGED_CLUSTER}
NAME READY STATUS RESTARTS AGE
klusterlet-registration-agent-598fd79988-jxx7n 1/1 Running 0 19d
klusterlet-work-agent-7d47f4b5c5-dnkqw 1/1 Running 0 19d
```
I discussed these changes with @mikeshng
Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
> doc: rearrange deploy steps for klusterlet

- content/en/concepts/managedclusterset.md
- content/zh/concepts/managedclusterset.md
The [documentation](https://open-cluster-management.io/concepts/managedclusterset/) specifies an incorrect syntax for the `clusteradm` command
Old syntax: ` clusteradm clusterset add`
New syntax: `clusteradm clusterset set`
```
clusteradm version
client		version	:v0.2.0
server release	version	:v1.23.4
```
> docs: fix clusteradm clusterset command syntax

- content/en/getting-started/integration/policy-controllers.md
- content/en/getting-started/integration/policy-framework.md
- content/zh/getting-started/integration/policy-controllers.md
- content/zh/getting-started/integration/policy-framework.md
The Policy installation tutorial seems to assume that you start the OCM
installation in the quick start and then progress to the Policy Framework
and then the Policy Controllers in one terminal session. This isn't
always the case, so redefining the required environment variables makes
this clearer.
> Redefine environment variables from other pages

- content/en/community/releases.md
- content/en/concepts/architecture.md
- content/en/concepts/managedcluster.md
- content/en/getting-started/integration/app-lifecycle.md
- content/en/scenarios/deploy-kubernetes-resources.md
- content/zh/community/releases.md
- content/zh/concepts/managedcluster.md
- content/zh/getting-started/integration/app-lifecycle.md
- content/zh/scenarios/deploy-kubernetes-resources.md
Follows from/depends on:
- https://github.com/open-cluster-management-io/clusteradm/pull/231
> Consistent flags/Fix spelling

- content/en/getting-started/integration/policy-controllers.md
- content/en/getting-started/integration/policy-framework.md
- content/zh/getting-started/integration/policy-controllers.md
- content/zh/getting-started/integration/policy-framework.md
The ManagedClusterAddOn objects must be deployed on the Hub for the
Policy Addon controller to create the correct ManifestWork objects.
> Fix the Policy addon installation instructions

- content/en/getting-started/integration/managed-serviceaccount.md
- content/zh/getting-started/integration/managed-serviceaccount.md
Replace `proxy` with `managed-serviceaccount`
Signed-off-by: zhujian <jiazhu@redhat.com>
> Fix typo in managed serviceaccount

- content/en/getting-started/installation/start-the-control-plane.md
close https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/328
I decided to write this in the "Prerequisite" section of the "Start the control plane" page.
I note below the approach I didn't adopt.
- Create a new page called "Supported Kubernetes Distributions".
Given the number of Kubernetes distributions, this seemed premature.
- "Kind is used for E2E testing and is 'supported' in that regard."
This is probably an unnecessary statement since few people create products with Kind(It's mainly for testing).
But if OCM is well tested in OpenShift (is it?) I think we can state "OCM is tested in OpenShift and Kind".
- "EKS support is ongoing."
There is some work toward this, but it seems to have stalled a bit. …
> Add limitation of Kubernetes distributions

- i18n/en.toml
- i18n/zh.toml
- themes/ocmTheme/layouts/partials/header.html
After merged we will have "Blog" also in header.
This is a practice followed by many projects, for example: 
The "Blog" and "Document" should be in the same level.
> Add blog to header.

- content/en/concepts/architecture.md
- content/en/concepts/managedcluster.md
- content/en/concepts/managedclusterset.md
- content/en/concepts/manifestwork.md
- content/en/contribute/_index.md
- content/en/getting-started/installation/start-the-control-plane.md
- content/zh/blog/registration-deepdive/_index.md
- content/zh/concepts/architecture.md
- content/zh/concepts/managedcluster.md
- content/zh/concepts/managedclusterset.md
- content/zh/concepts/manifestwork.md
- content/zh/contribute/_index.md
The related issue: https://github.com/open-cluster-management-io/OCM/issues/128
The fmt tool automatically delete some spaces in markdown files, but I also explicitly point out the changes using commits.
> Update links point to the repo ocm.

- themes/ocmTheme/layouts/_default/single.html
- themes/ocmTheme/layouts/partials/sidebar.html
- themes/ocmTheme/static/sidebar.js
- Remove unused sidebar toggle
- Use a consistent column class size
- Use templating so that the sidebar isn't post-processed and jumpy
- Adjust the sidebar script so that if a sub-page is opened that isn't in the sidebar, its parent is still highlighted
> Sidebar updates

- content/en/concepts/policy.md
- content/en/getting-started/integration/policy-controllers/_index.md
- content/en/getting-started/integration/policy-controllers/configuration-policy.md
- content/en/getting-started/integration/policy-controllers/gatekeeper.md
- content/en/getting-started/integration/policy-framework.md
- content/zh/concepts/policy.md
- content/zh/getting-started/integration/policy-controllers/_index.md
- content/zh/getting-started/integration/policy-controllers/configuration-policy.md
- content/zh/getting-started/integration/policy-controllers/gatekeeper.md
- content/zh/getting-started/integration/policy-framework.md
- Adds Gatekeeper references now that Policies can sync Gatekeeper manifests directly
- Also cleans up and reflows the Policy doc to make it all fit together
ref: https://issues.redhat.com/browse/ACM-5932
/cc @JustinKuli @mprahl @gparvin @yiraeChristineKim
> Add Gatekeeper integration

- content/en/concepts/clusterclaim.md
While reviewing the aforementioned article, I discerned a deficiency in Syntax highlighting implementation. 
Syntax highlighting entails the alteration of color and style attributes of source code, thereby enhancing its readability. Consequently, I undertook a comprehensive revision of all `YAML` files within the `ClusterClaim` article, integrating Syntax highlighting. 
This augmentation was executed with the primary objective of rendering the article content more accessible and comprehensible to its readership.
> Add syntax highlighting in clusterclaim

- content/en/scenarios/distribute-workload-with-placement.md
- content/zh/scenarios/distribute-workload-with-placement.md
1. [clusteradm](https://github.com/open-cluster-management-io/clusteradm) is updated,correct spelling of output table https://github.com/open-cluster-management-io/clusteradm/pull/218 ,Consequently, the output values are being reconfigured.
2. Adjusting proper indentation for improved formatting.
3. Modify the project name to avoid the use of abbreviations and rewrite it in its formal full form. [Argo CD](https://github.com/argoproj/argo-cd)
> Updated due to a clusteradm update.[2/2] 

- i18n/zh.toml
The `en.toml` file has been updated(https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/350), necessitating synchronization with `zh.toml`, and concurrent reformatting to ensure uniformity in layout.
> synchronization with `zh.toml`

- content/en/getting-started/quick-start/_index.md
I'm not sure why it's missing here since it's a prerequisite for the script...
If it looks good, I'll also need someone to help translate it over to the equivalent `zh` page since that page has been translated already.
> Add `clusteradm` install to "Quick Start"

- content/en/concepts/addon.md
- content/en/concepts/managedcluster.md
- content/en/concepts/managedclusterset.md
- content/en/concepts/manifestwork.md
- content/en/concepts/manifestworkreplicaset.md
- content/en/concepts/multicluster-controlplane.md
- content/en/concepts/placement.md
- content/en/concepts/policy.md
- content/zh/concepts/addon.md
- content/zh/concepts/clusterclaim.md
- content/zh/concepts/managedcluster.md
- content/zh/concepts/managedclusterset.md
- content/zh/concepts/manifestwork.md
- content/zh/concepts/manifestworkreplicaset.md
- content/zh/concepts/multicluster-controlplane.md
- content/zh/concepts/placement.md
- content/zh/concepts/policy.md
- i18n/en.toml
- i18n/zh.toml
- themes/ocmTheme/layouts/partials/sidebar.html
1. Add "ManifestWorkReplicaSet" and "Multicluster Control Plane" to sidebar.
2. Adjust the sidebar concepts sequence.
The output would be like:
> update the website sidebar content

- content/en/scenarios/distribute-workload-with-placement.md
- content/en/scenarios/migrate-workload-with-placement.md
- content/zh/scenarios/distribute-workload-with-placement.md
- content/zh/scenarios/migrate-workload-with-placement.md
- i18n/en.toml
- i18n/zh.toml
- themes/ocmTheme/layouts/partials/sidebar.html
Ref: 
https://github.com/open-cluster-management-io/ocm/issues/60
https://github.com/open-cluster-management-io/ocm/issues/61
> Migrate workload with placement

- content/en/developer-guides/addon.md
- content/zh/developer-guides/addon.md
Ref: https://github.com/open-cluster-management-io/ocm/issues/355
> update addon develop guide

- content/en/getting-started/integration/policy-controllers/configuration-policy.md
Signed-off-by: myan <myan@redhat.com>
The `config-policy-controller` pod constantly crashed with error message: 
```bash
$ oc logs config-policy-controller-574cb79566-zcpzd -n open-cluster-management-agent-addon
2024-06-05T10:01:38.380Z        info    setup   config-policy-controller/main.go:66     Using   {"OperatorVersion": "0.0.1", "GoVersion": "go1.21.10", "GOOS": "linux", "GOARCH": "amd64"}
2024-06-05T10:01:38.381Z        lvl-2   setup   config-policy-controller/main.go:223    Configured the watch namespace  {"watchNamespace": "managed"}
2024-06-05T10:01:38.399Z        error   setup   config-policy-controller/main.go:295    Unable to start manager {"error": "failed to determine if *v1beta1.OperatorPolicy is namespaced: failed to get restmapping: no matches for kind \"OperatorPolicy\" …
```
> config policy controller crashed without resource `OperatorPolicy`

- content/en/concepts/manifestwork.md
- content/zh/concepts/manifestwork.md
1. jsonraw type as feedback result
2. readonly strategy
> doc update on manifestwork

- .github/workflows/postsubmit.yml
- .github/workflows/presubmit.yml
- Makefile
The [hugo-wrapper](https://github.com/khos2ow/hugo-wrapper) has been inactive for years. 
Recently, when I use Apple Silicon laptop to run `make server`, it returns error:
```
(sleep 2; /usr/bin/open http://localhost:1313) &
./hugo server
Error: Unknown OS type or architecture
```
So change to let developer install hugo by themselves, and using a [active github action(1.5k starts and last update is 2 month ago)](https://github.com/peaceiris/actions-hugo) to setup hugo in github workflow
> Remove hugo wrapper.

- content/en/docs/getting-started/integration/cluster-proxy.md
Updates the cluster-proxy installation documentation to clarify that non-kind clusters (e.g., OpenShift) require setting the proxyServer.entrypointAddress value. Adds an example helm install command showing how to set this value.
> docs: clarify cluster-proxy installation for non-kind clusters

- content/en/docs/getting-started/integration/policy-controllers/configuration-policy.md
- content/en/docs/getting-started/integration/policy-framework.md
The commands are difficult to maintain and error-prone.
Also removes references to the *-sync controllers and some PlacementRule references.
> Remove "install from source" doc for GRC

- content/en/docs/concepts/manifestwork.md
Fix the old path used in https://multicluster.sigs.k8s.io/concepts/work-api/.
> Redirect manifestwork old path to new path

- content/en/_index.md
- content/en/blog/access-cluster-in-different-vps/index.md
- content/en/docs/concepts/add-on-extensibility/_index.md
- content/en/docs/concepts/add-on-extensibility/addon.md
- content/en/docs/concepts/architecture.md
- content/en/docs/concepts/cluster-inventory/_index.md
- content/en/docs/concepts/cluster-inventory/clusterclaim.md
- content/en/docs/concepts/cluster-inventory/managedcluster.md
- content/en/docs/concepts/cluster-inventory/managedclusterset.md
- content/en/docs/concepts/content-placement/_index.md
- content/en/docs/concepts/content-placement/placement.md
- content/en/docs/concepts/work-distribution/_index.md
- content/en/docs/concepts/work-distribution/manifestwork.md
- content/en/docs/concepts/work-distribution/manifestworkreplicaset.md
- content/en/docs/getting-started/integration/cluster-proxy.md
- content/en/docs/getting-started/integration/multicluster-controlplane.md
- content/en/docs/getting-started/integration/policy-controllers/_index.md
- content/en/docs/getting-started/integration/policy-controllers/configuration-policy.md
- content/en/docs/getting-started/integration/policy-framework.md
- content/en/docs/getting-started/integration/policy.md
- content/en/docs/scenarios/deploy-kubernetes-resources.md
- content/en/docs/scenarios/distribute-workload-with-placement.md
- content/en/docs/scenarios/extending-managed-clusters.md
- content/en/docs/scenarios/integration-with-argocd.md
More and more fields and operations are added to OCM, like rollout strategy, placement strategy, addon template, manfestworkreplicaset, etc, they are all mixed in the existing "Concept" section. This increases the mental load for OCM beginners, and makes users confused about like, addon vs manifestwork, addon-framework vs addon template. 
- Concept: 
- From @mikeshng: surface our core concepts: "Cluster Inventory", "Work Distribution", "Content Placement", "Add-On Extensibility"
- concept should focus on what it is and how it works, the relationship between the key concepts. For example, what is ManagedCluster, how to register it to the hub, and how the cert rotates. The complex operations should move to quick start or use scenarios.
move policy and control plan to quick start -> addon & …
> refine the website structure

- content/en/docs/concepts/add-on-extensibility/addon.md
- content/en/docs/concepts/cluster-inventory/managedcluster.md
- content/en/docs/concepts/cluster-inventory/managedclusterset.md
- content/en/docs/concepts/content-placement/placement.md
- content/en/docs/faq/_index.md
Ref: https://github.com/open-cluster-management-io/ocm/issues/781
> add faq page

- content/en/_index.md
- content/en/docs/getting-started/integration/policy-controllers/_index.md
- content/en/docs/getting-started/integration/policy-controllers/configuration-policy.md
- content/en/docs/getting-started/integration/policy-controllers/policy-framework.md
- content/en/docs/getting-started/integration/policy-controllers/policy.md
- content/en/docs/getting-started/quick-start/_index.md
Ref: https://github.com/open-cluster-management-io/ocm/issues/781
> merge policy into one section

- content/en/docs/getting-started/integration/policy-controllers/_index.md
- content/en/docs/getting-started/integration/policy-controllers/configuration-policy.md
- content/en/docs/getting-started/integration/policy-controllers/gatekeeper.md
- content/en/docs/getting-started/integration/policy-controllers/policy-framework.md
- content/en/docs/getting-started/integration/policy-controllers/policy.md
With the consolidated section, it was necessary to redefine the landing page.
Followup to:
- #449
> Reconfigure Policy

- README.md
Update README to include a note about redirecting requests for open-cluster-management.io/helm-charts to the GitHub repository
Related PR: https://github.com/open-cluster-management-io/helm-charts/pull/20
> Add redirect for Helm charts to README

- content/en/docs/concepts/content-placement/placement.md
ref: https://github.com/open-cluster-management-io/ocm/issues/987
> add placement cel examples

- content/en/_index.md
See the BLUE BUTTON with Bot icon at the bottom right conner.
It's not an embeded chat box, it will direct user to this page: https://deepwiki.com/open-cluster-management-io/ocm
> Add a button in the main page to link to deepwiki ocm page.

- content/en/docs/getting-started/integration/fleetconfig-controller.md
- content/en/docs/getting-started/quick-start/_index.md
This PR updates the installation quick start to reference the [FleetConfig Controller](https://github.com/open-cluster-management-io/lab/tree/main/fleetconfig-controller) and adds a new FleetConfig Controller page.
> 📖  add FleetConfig Controller page

- content/en/docs/developer-guides/addon.md
The section about disabling addons showed an unsupported flag `--all-clusters` flag. This PR removes it.
> 📖 : clean up addon cmd examples

- content/en/docs/getting-started/installation/register-a-cluster.md
Noticed a broken link while using the docs. It was missing the `/docs` prefix. Also updated to use the `{{< ref ... >}}` templating used elsewhere in docs links.
> Fix broken link

- content/en/docs/getting-started/installation/register-a-cluster.md
- content/en/docs/getting-started/installation/start-the-control-plane.md
fix https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/issues/506
> Set resources request/limit for hub and agent

- assets/scss/_styles_project.scss
- hugo.yaml
Add a scarf pixel to the website to provide high-level web traffic insights for project maintainers so they can better understand how docs are being read and used. 
Scarf doesn't store any personally identifiable information and is GDPR and SOC 2 Type 2 compliant, as well as "approved" for use by LF and CNCF and Apache.
> add scarf pixel to website
